language: julia
os:
    - linux
julia:
    - 0.5
    - nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - libgmp-dev
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --check-bounds=yes -e 'Pkg.init(); Pkg.add("JuMP"); Pkg.clone(pwd()); Pkg.build("JuMPChance"); Pkg.test("JuMPChance"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("JuMPChance")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
